project_id = "sjtgecslgpldlsycaazt"

[functions.rewrite]
verify_jwt = true

[functions.feedback]
verify_jwt = true

[functions.impact-index]
verify_jwt = true

[functions.realtime-token]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.elevenlabs-signed-url]
verify_jwt = false